### ISSUE TITLE
Dispersion SimpleDftD3 missing from manual

### ISSUE THREAD

**Issue by aradi** [dftbplus/dftbplus#838] opened 2021-08-17 13:15 UTC
**Describe the bug**
The dispersion model SimpleDftD3 is missing from the manual.

**To Reproduce**
Open the manual.

**Expected behaviour**
Finding a section about the SimpleDftD3 model. :wink:

**Comment by awvwgk** [comment] 2021-08-19 09:12
Duplicate of #791

**Closed** 2021-08-19 09:12 UTC
