### ISSUE TITLE
DFTB-D4 crash 

### ISSUE THREAD

**Issue by dveclani** [dftbplus/dftbplus#816] opened 2021-07-14 17:56 UTC
Dear users,

I am Daniele Veclani and I'm new to DFTB+ world. I want to use DFTB+ to perfom some calculation with DFT-D4. I tried to create an input file (attached) that included D4 dispersion corrections  by adding the following lines:

```
  Dispersion = DftD4 {
   s8 = 2.7711819
   s9 = 0
   a1 = 0.4681712
   a2 = 5.2918629
  }
}
```

However the calculation crashes immediately with the following error:

```
 Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x5654f3f in ???
#1  0x8fa5f8 in __dftbp_coordnumber_MOD_getcoordinationnumber._omp_fn.0
        at /home/aradi/ramdisk/gnu/dftb+/prog/dftb+/lib_dftb/coordnumber.f90:488
#2  0x562644d in gomp_thread_start
        at ../.././libgomp/team.c:123
#3  0x564a74d in ???
#4  0x56fbbf2 in ???
#5  0xffffffffffffffff in ???
srun: error: cerbero: task 0: Segmentation fault (core dumped)
```

I run this calculation with a SLUM script (attached). If anyone could offer some information about this error, or an example of an input file which can be used to calculate with DFTB-D4, I’ll be very appreciated.
[Files.zip](https://github.com/dftbplus/dftbplus/files/6818096/Files.zip)

Best regerds,
Daniele Veclani

**Comment by awvwgk** [comment] 2021-07-14 18:42
Just tried running the above example and couldn't reproduce the issue. Try
```
ulimit -s unlimited
OMP_STACKSIZE=8G dftb+
```

**Comment by dveclani** [comment] 2021-07-15 07:14
thank you very much, I solved the problem following your advice.

Best,
Daniele.

**Comment by aradi** [comment] 2021-07-15 07:18
I'll close the issue then. @dveclani Would you mind to post the solution to the DFTB+ devel user group as well, so that it can be also found in its archive? Thx!

**Closed by aradi** 2021-07-15 07:18 UTC
